version: '3.0'
services:
    postgres: 
        build: 
            context: ./postgres
            dockerfile: ./Dockerfile
        ports:
            - "5432:5432"
        dns: 
            - 127.0.0.1
            - 64.102.6.247
            - 171.70.168.183
            - 173.36.131.10
        network_mode: "bridge"
    server: 
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        volumes: 
            - ./server:/src
        dns: 
            - 127.0.0.1
            - 64.102.6.247
            - 171.70.168.183
            - 173.36.131.10
        network_mode: "bridge"
        links:
            - "postgres:postgres"
        depends_on:
            - postgres
    client: 
        build:
            context: ./client
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        volumes: 
            - ./client:/src
        dns: 
            - 127.0.0.1
            - 64.102.6.247
            - 171.70.168.183
            - 173.36.131.10
        network_mode: "bridge"
        links:
            - "server:server"
        depends_on:
            - server
