version: '3.3'
services:
    postgres: 
        build: 
            context: ./postgres
            dockerfile: ./Dockerfile
        ports:
            - "5432:5432"
        dns: 
            - 127.0.0.1
        network_mode: "bridge"
    server: 
        build:
            context: ./server
            dockerfile: ./Dockerfile
        command: nodemon app.js
        ports:
            - "3000:3000"
        volumes: 
            - ./server:/src
        dns: 
            - 127.0.0.1
        network_mode: "bridge"
        links:
            - "postgres:postgres"
        depends_on:
            - postgres
    client: 
        build:
            context: ./client
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        volumes: 
            - ./client/conf.d:/etc/nginx/conf.d
            - ./client/static:/usr/share/nginx/html
        network_mode: "bridge"
        links:
            - "server:server"
        depends_on:
            - server
