version: '3.3'
services:
    postgres: 
        build: 
            context: ./postgres
            dockerfile: ./Dockerfile
        dns: 
            - 127.0.0.1
        network_mode: "bridge"
        volumes: 
            - ./postgres/data_persist:/var/lib/postgresql/data
    server: 
        build:
            context: ./server
            dockerfile: ./Dockerfile
        command: nodemon --inspect=0.0.0.0:9229 src/app.js
        ports:
            - "9229:9229"
        volumes: 
            - ./server/src:/server/src
        dns: 
            - 127.0.0.1
        network_mode: "bridge"
        links:
            - "postgres:postgres"
        depends_on:
            - postgres
    client: 
        build:
            context: ./client
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        volumes: 
            - ./client/conf.d:/etc/nginx/conf.d
        network_mode: "bridge"
        links:
            - "server:server"
        depends_on:
            - server
