resources:
- name: jprdy-git
  type: git
  icon: github
  source:
    uri: https://github.com/taylordeckard/jeopardy.git
    username: (("github".access_token))
    password: x-oauth-basic
    branch: master
- name: client-repo
  type: registry-image
  icon: docker
  source:
    repository: warbler.docker-registry/jprdy-client
    username: ((docker_registry.username))
    password: ((docker_registry.password))
    ca_certs:
    - ((docker_registry.ca))
- name: server-repo
  type: registry-image
  icon: docker
  source:
    repository: warbler.docker-registry/jprdy-server
    username: ((docker_registry.username))
    password: ((docker_registry.password))
    ca_certs:
    - ((docker_registry.ca))

jobs:
- name: build
  plan:
  - get: jprdy-git
    trigger: true
  - task: compile-client
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: node
          tag: 8-alpine
      inputs:
      - name: jprdy-git
      outputs:
      - name: compiled-client
      run:
        path: ash
        args:
        - -c
        - |
          set -e
          cp -r jprdy-git/client/* compiled-client/.
          cd jprdy-git/client/vue
          npm i
          npm run build
          cd ../../../compiled-client
          mkdir -p static
          cp -r jprdy-git/client/vue/dist/* static/.
  - in_parallel:
    - task: build-client
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        inputs: 
        - name: compiled-client
        outputs:
        - name: client-image
        run:
          path: build
        params:
          CONTEXT: compiled-client
    - task: build-server
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: vito/oci-build-task
        inputs: 
        - name: jprdy-git
        outputs:
        - name: server-image
        run:
          path: build
        params:
          CONTEXT: jprdy-git/server
  - in_parallel:
    - put: client-repo
      params:
        image: client-image/image.tar
    - put: server-repo
      params:
        image: server-image/image.tar
